### ISSUE TITLE
Government Design Principles Poster download only includes 8 pages

### ISSUE THREAD

**Issue by danielwestlake** [alphagov/govdesign#9]
Government Design Principles Poster download only includes 8 pages. There should be 10 pages to include all 10 posters

Download available at:
https://github.com/alphagov/govdesign/blob/master/Poster_GovernmentDesignPrinciples.pdf

**Comment by martin-jordan** [comment]
I cannot reproduce that issue. Looking at the PDF behind the link, I can see all 10 pages and principles. Please try again on another browser or possibly a more stable internet connection.
